### ISSUE TITLE
[low prio] 做一个简单的机器人的外形

### ISSUE THREAD

**Issue by nintendolintao** [ttchin/FaceDetected#11]
例如下面这个例子来自 <https://www.oreilly.com/learning/how-to-build-a-robot-that-sees-with-100-and-tensorflow>

![one example](https://d3ansictanv2wj.cloudfront.net/Figure_5-5b104cf7a53a9c1ee95110b78fb14256.jpg)

**Comment by ttchin** [comment]
tony提供大白模型装饰
