### ISSUE TITLE
完成脸部识别开始, 进行中和结束后的发声功能

### ISSUE THREAD

**Issue by nintendolintao** [ttchin/FaceDetected#5]
如果可以中文发音的话演示效果会更好

**Comment by nintendolintao** [comment]
该task的主要目的是完成在电脑上的面部识别的验证, 尽量保证识别的速度和准确率.

**Comment by nintendolintao** [comment]
From <http://tensordata.cn/t/tensorflow/88>
中文语音输出：在树莓派上安装sdcv,进行英汉翻译。用ekho进行中文转语音。Ekho（余音）是一个免费、开源的中文语音合成软件。它目前支持粤语、普通话（国语）、诏安客语、藏语、雅言（中国古代通用语）和韩语（试验中），英语则通过eSpeak或Festival间接实现。Ekho支持Linux、Windows和Android平台。

**Comment by nintendolintao** [comment]
可否使用蓝牙音箱发声? (注: 妥尼可提供一个蓝牙音箱)

**Comment by ttchin** [comment]
leo准备一些幽默风趣的音频，在识别过程中随机播放，减少等待过程中的尴尬。

**Comment by nintendolintao** [comment]
Espeak

http://www.instructables.com/id/Make-your-Raspberry-Pi-speak/

**Comment by nintendolintao** [comment]
为了提高中文名字的发音准确率 可以考虑使用  威妥玛式拼音法

https://baike.baidu.com/item/%E5%A8%81%E5%A6%A5%E7%8E%9B%E5%BC%8F%E6%8B%BC%E9%9F%B3%E6%B3%95

**Comment by nintendolintao** [comment]
英文版的场景已经上传到

https://github.com/ttchin/FaceDetected/blob/master/SCENARIO_EN.md
