### ISSUE TITLE
采集尽可能多的同事的照片, 训练一个demo用的模型

### ISSUE THREAD

**Issue by nintendolintao** [ttchin/FaceDetected#8]
最新的CapturePictures已经更新并增强了易用性, 采集同事照片已经非常简单

**Comment by nintendolintao** [comment]
From <https://www.zhihu.com/question/27790364>

> 如果你想要达到Google这种等级的表现的话，你需要上百万张高清无码大图。在机器学习这个领域中，**有更多的数据总比一个更好的算法更重要.** 现在你知道为什么谷歌总是乐于给你提供无限量免费图片存储了吧？

**Comment by ttchin** [comment]
想要精确的识别一个陌生人，最少需要1000个人以上的训练集。在目前的条件下无法做到，只能识别训练集的人物。

**Comment by ttchin** [comment]
请大家今天上传照片（最好有生活照）上传到share folder作为训练素材。

**Comment by ttchin** [comment]
Ye负责收集部门内其他同事的照片作为训练素材。
zhentao,yang dan, feng fei, fa qi,linli, lan ying.
